apiVersion: v1
kind: ConfigMap
metadata:
  name: myapi-config
data:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MyDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
